[mysql]
# pre环境数据库
host=mariadb-master-test.sndu.cn
port=3306
user=unionid
password=unionid
database=unionid

# 定义的pms接口默认值
[apt_update]
# 回填接口地址
write_testdate_to_pms=http://10.0.10.200:3000/api/v1/zbox/result
# 产品ID
product_id=
# 测试单ID
task_id=
# 默认操作用户名
username=

[update_status]
# pre环境
secret_key=0c81953700b34aefb3f2f28a1bca6520
# dev环境
#secret_key=12344566

[license_sync]
account=15007141571
password=wyb19970803
MachineID=4167f732ea504669a0107afbfde6ff96

[update_platform_path]
admin_path_pre=http://gray-update-admin-pre.uniontech.com

[linglong]
qliyun = https://api.linglong.space
